type Category {
    name: String!
    
    resource: [Resource] @relation
}

type Resource {
    title: String!
    type: String!

    website: Website
    video: Video

    categoryRef: Category
}

type Website {
    url: String!
    name: String!

    resourceRef: Resource
}

type Video {
    url: String!
    title: String

    resourceRef: Resource
}